version: '3.9'

services:

  client-processing:
    build: ./clientProcessing
    container_name: client-processing
    ports:
      - "8081:8081"
    environment:
      DB_HOST: client-db
      DB_PORT: 5432
      DB_NAME: client_processing
      DB_USER: postgres
      DB_PASSWORD: admin
    depends_on:
      - client-db

  client-db:
    image: postgres:15
    container_name: client-db
    environment:
      POSTGRES_DB: client_processing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - client-data:/var/lib/postgresql/data

  account-processing:
    build: ./accountProcessing
    container_name: account-processing
    ports:
      - "8082:8082"
    environment:
      DB_HOST: account-db
      DB_PORT: 5432
      DB_NAME: account_processing
      DB_USER: postgres
      DB_PASSWORD: admin
    depends_on:
      - account-db

  account-db:
    image: postgres:15
    container_name: account-db
    environment:
      POSTGRES_DB: account_processing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - account-data:/var/lib/postgresql/data

  credit-processing:
    build: ./creditProcessing
    container_name: credit-processing
    ports:
      - "8083:8083"
    environment:
      DB_HOST: credit-db
      DB_PORT: 5432
      DB_NAME: credit_processing
      DB_USER: postgres
      DB_PASSWORD: admin
    depends_on:
      - credit-db

  credit-db:
    image: postgres:15
    container_name: credit-db
    environment:
      POSTGRES_DB: credit_processing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - credit-data:/var/lib/postgresql/data

volumes:
  client-data:
  account-data:
  credit-data: