spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/client_processing
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

t1:
  kafka:
    bootstrap:
      server: localhost:9092